// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbt0ylEhy3SWwl__ouWWxVYA07GQlEsFE',
    appId: '1:106886147486:web:e698992f7b334a8e453a8f',
    messagingSenderId: '106886147486',
    projectId: 'fithub-5df39',
    authDomain: 'fithub-5df39.firebaseapp.com',
    storageBucket: 'fithub-5df39.appspot.com',
    measurementId: 'G-7V6SFCC26G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX7CwRezoZ6uiKopMVJkZwrGlFt1w-UwQ',
    appId: '1:106886147486:android:2033987c26aa7d87453a8f',
    messagingSenderId: '106886147486',
    projectId: 'fithub-5df39',
    storageBucket: 'fithub-5df39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnpsKw5xSCLYeiBCbIrf8HA6ekqLDInw0',
    appId: '1:106886147486:ios:43e2dfe2fdbc8db3453a8f',
    messagingSenderId: '106886147486',
    projectId: 'fithub-5df39',
    storageBucket: 'fithub-5df39.appspot.com',
    androidClientId: '106886147486-oc2v7hurdq9hgf8282m8sitt3p1h00b9.apps.googleusercontent.com',
    iosClientId: '106886147486-omkl2lohpuqfl67qlctabah7rct8rdsj.apps.googleusercontent.com',
    iosBundleId: 'com.fithub.groupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnpsKw5xSCLYeiBCbIrf8HA6ekqLDInw0',
    appId: '1:106886147486:ios:43e2dfe2fdbc8db3453a8f',
    messagingSenderId: '106886147486',
    projectId: 'fithub-5df39',
    storageBucket: 'fithub-5df39.appspot.com',
    androidClientId: '106886147486-oc2v7hurdq9hgf8282m8sitt3p1h00b9.apps.googleusercontent.com',
    iosClientId: '106886147486-omkl2lohpuqfl67qlctabah7rct8rdsj.apps.googleusercontent.com',
    iosBundleId: 'com.fithub.groupProject',
  );
}
